language: php

php:
  - 5.4
  - 5.5
  - 5.6

# environment variable used in test suite
env: TEST_ENVIRONMENT=travis

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# install dependencies
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
# codeception
  - travis_retry composer global require "codeception/codeception:~2.0" "codeception/specify:*" "codeception/verify:*"

before_script:
  - cd tests
  - mysql -e 'create database dektrium_test;'
  - php codeception/_app/yii migrate/up --interactive=0
  - codecept build

script: codecept run
