<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Before your account is activated, we need you to confirm your email address' => 'Для завершения регистрации вы должны подтвердить адрес электронной почты',
  'Confirm' => 'Подтвердить',
  'Create user' => 'Создать пользователя',
  'Delete recovery tokens' => 'Удалить токены',
  'Delete user' => 'Удалить пользователя',
  'Hi there,' => 'Здравствуйте,',
  'If you have problems, please paste the above URL into your web browser' => 'Если по каким-то причинам ссылка выше нe работает, вставьте следующий адрес в адресную строку браузера',
  'In order to complete this request, we need you to verify that you initiated this request' => 'Если вы не регистрировались, пожалуйста, проигнорируйте это письмо',
  'Last login at {0, date, MMMM dd, YYYY HH:mm} from {1}' => 'Последняя авторизация {0, date, MMMM dd, YYYY HH:mm} с {1}',
  'Login' => 'Логин',
  'Manage users' => 'Управление пользователями',
  'P.S. If you did not request to reset your password, please disregard this message. Your account is safe.' => 'Если вы не запрашивали сброс пароля, проигнорируйте это письмо. Ваш аккаунт в безопасности',
  'Please click the link below to complete your password reset' => 'Чтобы восстановить пароль, нажмите на ссылку ниже',
  'Please complete password reset' => 'Восстановление пароля',
  'Please confirm your account' => 'Активация аккаунта',
  'Registered at {0, date, MMMM dd, YYYY HH:mm} from {1}' => 'Зарегистрирован {0, date, MMMM dd, YYYY HH:mm} с {1}',
  'Registration ip' => 'Регистрационный IP',
  'Registration time' => 'Время регистрации',
  'To complete your registration, please click the link below' => 'Чтобы активировать аккаунт, нажмите на ссылку ниже',
  'User has not logged in yet' => 'Пользователь еще не авторизовывался',
  'Welcome to {sitename}' => 'Добро пожаловать на {sitename}',
  'You have recently requested to reset your password on {sitename}' => 'Вы запросили восстановление пароля на {sitename}',
  'You recently registered for a new account on {sitename}' => 'Вы зарегистрировались на сайте {sitename}',
  'Your may log in with following credentials' => 'Вы можете авторизоваться со следующими данными',
  '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, MMMM dd, YYYY HH:mm}',
  'Account has been created' => 'Вы были зарегистрированы',
  'Awesome! Your account has been created' => 'Вы были зарегистрированы',
  'Awesome! Your password has been reset' => 'Ваш пароль был сброшен',
  'Awesome, almost there!' => 'Почти готово!',
  'Awesome, almost there! We need to confirm your email address' => 'Почти готово! Вам необходимо активировать ваш аккаунт',
  'Confirmation needed' => 'Необходима активация аккаунта',
  'Confirmation token is invalid' => 'Сссылка для активации аккаунта устарела',
  'Didn\'t receive confirmation message?' => 'Не пришло письмо?',
  'Email' => 'Email',
  'Email or username' => 'Email или имя пользователя',
  'Forgot password?' => 'Забыли пароль?',
  'If you\'re having troubles, you can resend it by clicking the link below:' => 'Если писмьмо не пришло, вы можете запросить новое, нажав на ссылку ниже',
  'Invalid login or password' => 'Неправильный логин или пароль',
  'Log in' => 'Войти',
  'Password' => 'Пароль',
  'Password has been reset' => 'Пароль был сброшен',
  'Password recovery' => 'Восстановление пароля',
  'Please check your email and click the confirmation link to complete your registration.' => 'Пожалуйста, проверьте ваш почтовый ящик и нажмите на ссылку, чтобы завершить регистрацию',
  'Recovery message sent' => 'Письмо со ссылкой для смены пароля было отправлено',
  'Recovery token is invalid' => 'Сссылка для смены пароля устарела',
  'Register' => 'Зарегистрироваться',
  'Remember me next time' => 'Запомнить меня',
  'Request new confirmation message' => 'Повторная отправка инструкций',
  'Reset password' => 'Сбросить пароль',
  'Send' => 'Отправить',
  'This account has already been confirmed' => 'Этот аккаунт уже был активирован',
  'Username' => 'Имя пользователя',
  'Verification Code' => 'Код подтверждения',
  'We\'re sorry but your confirmation token is invalid. You can request new token by clicking the link below:' => 'К сожалению эта ссылка устарела. Вы можете запросить новую, кликнув по ссылке ниже',
  'You can log in using your credentials now' => 'Теперь вы можете войти, используя ваши логин и пароль',
  'You can log in using your new password now' => 'Теперь вы можете войти, используя ваш новый пароль',
  'You have been sent an email with instructions on how to reset your password.' => 'Вам были отправлены инструкции по смене пароля',
  'You must confirm your account before logging in' => 'Вы должны сначала активировать ваш аккаунт',
  'Your account has been confirmed' => 'Ваш аккаунт был активирован',
);
