#!/usr/bin/env php
<?php

require __DIR__ . '/../_init.php';
require(VENDOR_DIR . '/yiisoft/yii2/Yii.php');

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$config = require(__DIR__ . '/config/console.php');

$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);